/* =====================================================================
   Kumbhak content pack — techniques + i18n (English + Hindi).
   Data-only. Loaded as a classic script before the app (window global),
   so it works over file:// and http:// without module/CORS issues.
   Add a language by adding a key under `strings` and a `<lang>` block
   to each technique's `i18n`.
   ===================================================================== */
window.KUMBHAK_CONTENT = {

  // Free techniques (everything else is Pro). One pranayama is free on
  // purpose — it showcases the India wedge and feeds the upgrade funnel.
  freeIds: ["box", "calm", "anulom_vilom"],

  // Onboarding goal → starter technique (must be a FREE id so the first
  // session never hits the paywall).
  goalMap: { sleep:"calm", stress:"anulom_vilom", focus:"box", energy:"box" },

  // Streak celebration milestones (days).
  milestones: [3, 7, 14, 30, 60, 100],

  // AI coach — moods offered in the check-in, the minute options, and the
  // local fallback technique per mood (used when no AI backend/key is set).
  aiMoods: [
    { id: "stressed", icon: "😰" },
    { id: "anxious", icon: "😟" },
    { id: "tired", icon: "😴" },
    { id: "focus", icon: "🎯" },
    { id: "sleep", icon: "🌙" },
    { id: "okay", icon: "🙂" },
  ],
  aiMinutes: [2, 5, 10],
  moodTech: {
    stressed: { inhale: 4, holdIn: 0, exhale: 7, holdOut: 0, rest: 0 },
    anxious:  { inhale: 4, holdIn: 0, exhale: 6, holdOut: 0, rest: 0 },
    tired:    { inhale: 4, holdIn: 2, exhale: 4, holdOut: 0, rest: 0 },
    focus:    { inhale: 4, holdIn: 4, exhale: 4, holdOut: 4, rest: 0 },
    sleep:    { inhale: 4, holdIn: 7, exhale: 8, holdOut: 0, rest: 0 },
    okay:     { inhale: 5.5, holdIn: 0, exhale: 5.5, holdOut: 0, rest: 0 },
  },

  // Guided multi-day programs (Pro). Each day references a technique id (+ optional
  // rounds override). Day titles are generated, so adding days needs no new strings.
  programs: [
    { id:"sleep7", icon:"🌙", color:"#b388ff",
      i18n:{ en:{name:"7 Nights to Sleep", desc:"Wind down each evening with calming breath"},
             hi:{name:"7 रातें बेहतर नींद", desc:"हर शाम शांत श्वास के साथ आराम करें"},
             or:{name:"7 ରାତିରେ ଭଲ ନିଦ୍ରା", desc:"ପ୍ରତି ସନ୍ଧ୍ୟାରେ ଶାନ୍ତ ଶ୍ୱାସ ସହ ବିଶ୍ରାମ"} },
      days:[ {tech:"calm"}, {tech:"478"}, {tech:"calm",rounds:12}, {tech:"bhramari"}, {tech:"478"}, {tech:"calm",rounds:14}, {tech:"478"} ] },
    { id:"calm7", icon:"🌿", color:"#43d9a3",
      i18n:{ en:{name:"7 Days to Calm", desc:"Ease anxiety with balancing pranayama"},
             hi:{name:"7 दिन शांति के", desc:"संतुलनकारी प्राणायाम से चिंता घटाएँ"},
             or:{name:"7 ଦିନରେ ଶାନ୍ତି", desc:"ସନ୍ତୁଳନକାରୀ ପ୍ରାଣାୟାମରେ ଚିନ୍ତା କମାନ୍ତୁ"} },
      days:[ {tech:"anulom_vilom"}, {tech:"coherent"}, {tech:"bhramari"}, {tech:"anulom_vilom",rounds:14}, {tech:"box"}, {tech:"coherent",rounds:16}, {tech:"bhramari",rounds:10} ] },
    { id:"focus7", icon:"🎯", color:"#4f8cff",
      i18n:{ en:{name:"7 Days to Focus", desc:"Sharpen attention before work"},
             hi:{name:"7 दिन एकाग्रता के", desc:"काम से पहले ध्यान तेज़ करें"},
             or:{name:"7 ଦିନରେ ଏକାଗ୍ରତା", desc:"କାମ ପୂର୍ବରୁ ଧ୍ୟାନ ତୀକ୍ଷ୍ଣ କରନ୍ତୁ"} },
      days:[ {tech:"box"}, {tech:"box",rounds:10}, {tech:"coherent"}, {tech:"box",rounds:12}, {tech:"ujjayi"}, {tech:"coherent",rounds:16}, {tech:"box",rounds:14} ] },
  ],

  // Generalized phases (seconds): inhale → holdIn → exhale → holdOut, + rest
  // between rounds. A 0 means the phase is skipped.
  techniques: [
    { id:"box", icon:"⬛", color:"#4f8cff", rounds:8,
      pattern:{inhale:4,holdIn:4,exhale:4,holdOut:4,rest:0},
      i18n:{ en:{name:"Box Breathing", desc:"Calm focus · equal 4-count", note:"Inhale, hold, exhale, hold — all equal."},
             hi:{name:"बॉक्स श्वास", desc:"एकाग्रता · सम 4-गिनती", note:"साँस लें, रोकें, छोड़ें, रोकें — सब बराबर।"},
             or:{name:"ବକ୍ସ ଶ୍ୱାସ", desc:"ଏକାଗ୍ରତା · ସମାନ 4-ଗଣନା", note:"ଶ୍ୱାସ ନିଅନ୍ତୁ, ଧରନ୍ତୁ, ଛାଡ଼ନ୍ତୁ, ଧରନ୍ତୁ — ସବୁ ସମାନ।"} } },

    { id:"calm", icon:"🍃", color:"#4dd0e1", rounds:10,
      pattern:{inhale:4,holdIn:0,exhale:6,holdOut:0,rest:0},
      i18n:{ en:{name:"Calm 4-6", desc:"Longer exhale to relax", note:"A long exhale calms the nervous system."},
             hi:{name:"शांति 4-6", desc:"लंबी साँस छोड़ें, आराम पाएँ", note:"लंबी साँस छोड़ना तंत्रिका तंत्र को शांत करता है।"},
             or:{name:"ଶାନ୍ତି 4-6", desc:"ଲମ୍ବା ନିଶ୍ୱାସ, ଆରାମ", note:"ଲମ୍ବା ନିଶ୍ୱାସ ସ୍ନାୟୁତନ୍ତ୍ରକୁ ଶାନ୍ତ କରେ।"} } },

    { id:"anulom_vilom", icon:"🌀", color:"#43d9a3", rounds:10,
      pattern:{inhale:4,holdIn:0,exhale:4,holdOut:0,rest:0},
      i18n:{ en:{name:"Anulom Vilom", desc:"Alternate-nostril balance", note:"Inhale one nostril, exhale the other — switch each round."},
             hi:{name:"अनुलोम विलोम", desc:"नाड़ी शोधन · संतुलन", note:"एक नथुने से साँस लें, दूसरे से छोड़ें — हर राउंड बदलें।"},
             or:{name:"ଅନୁଲୋମ ବିଲୋମ", desc:"ନାଡ଼ୀ ଶୋଧନ · ସନ୍ତୁଳନ", note:"ଗୋଟିଏ ନାକରେ ଶ୍ୱାସ ନିଅନ୍ତୁ, ଅନ୍ୟରେ ଛାଡ଼ନ୍ତୁ — ପ୍ରତି ରାଉଣ୍ଡ ବଦଳାନ୍ତୁ।"} } },

    { id:"478", icon:"🌙", color:"#b388ff", rounds:6,
      pattern:{inhale:4,holdIn:7,exhale:8,holdOut:0,rest:0},
      i18n:{ en:{name:"4-7-8 Relax", desc:"Wind down & sleep", note:"The classic relaxing breath for sleep."},
             hi:{name:"4-7-8 विश्राम", desc:"आराम व नींद", note:"नींद के लिए प्रसिद्ध शांत श्वास।"},
             or:{name:"4-7-8 ବିଶ୍ରାମ", desc:"ଆରାମ ଓ ନିଦ୍ରା", note:"ନିଦ୍ରା ପାଇଁ ପ୍ରସିଦ୍ଧ ଶାନ୍ତ ଶ୍ୱାସ।"} } },

    { id:"coherent", icon:"💗", color:"#5ec5a0", rounds:12,
      pattern:{inhale:5.5,holdIn:0,exhale:5.5,holdOut:0,rest:0},
      i18n:{ en:{name:"Coherent", desc:"Resonant 5.5 · balance HRV", note:"Smooth 5.5-second breaths balance the heart."},
             hi:{name:"कोहेरेंट", desc:"समस्वर 5.5 · हृदय संतुलन", note:"सहज 5.5-सेकंड श्वास हृदय को संतुलित करती है।"},
             or:{name:"କୋହେରେଣ୍ଟ", desc:"ସମସ୍ୱର 5.5 · ହୃଦୟ ସନ୍ତୁଳନ", note:"ସ୍ଥିର 5.5-ସେକେଣ୍ଡ ଶ୍ୱାସ ହୃଦୟକୁ ସନ୍ତୁଳିତ କରେ।"} } },

    { id:"bhramari", icon:"🐝", color:"#ffb74d", rounds:8,
      pattern:{inhale:4,holdIn:0,exhale:6,holdOut:0,rest:0},
      i18n:{ en:{name:"Bhramari (Bee)", desc:"Humming exhale · soothes", note:"Hum softly like a bee on each exhale."},
             hi:{name:"भ्रामरी", desc:"गुंजन श्वास · शांति", note:"हर साँस छोड़ते समय भौंरे जैसा गुंजन करें।"},
             or:{name:"ଭ୍ରମରୀ", desc:"ଗୁଞ୍ଜନ ଶ୍ୱାସ · ଶାନ୍ତି", note:"ପ୍ରତି ନିଶ୍ୱାସରେ ଭ୍ରମର ପରି ଗୁଞ୍ଜନ କରନ୍ତୁ।"} } },

    { id:"ujjayi", icon:"🌊", color:"#4dd0e1", rounds:12,
      pattern:{inhale:5,holdIn:0,exhale:5,holdOut:0,rest:0},
      i18n:{ en:{name:"Ujjayi (Ocean)", desc:"Ocean-sound breath", note:"Gently constrict the throat for an ocean sound."},
             hi:{name:"उज्जायी", desc:"सागर-ध्वनि श्वास", note:"गले को हल्का सिकोड़ें, सागर जैसी ध्वनि बनाएँ।"},
             or:{name:"ଉଜ୍ଜାୟୀ", desc:"ସମୁଦ୍ର-ଧ୍ୱନି ଶ୍ୱାସ", note:"ଗଳା ହାଲୁକା ସଙ୍କୁଚିତ କରି ସମୁଦ୍ର ପରି ଧ୍ୱନି କରନ୍ତୁ।"} } },

    { id:"sheetali", icon:"❄️", color:"#7fd4ff", rounds:8,
      pattern:{inhale:4,holdIn:0,exhale:6,holdOut:0,rest:0},
      i18n:{ en:{name:"Sheetali (Cooling)", desc:"Cooling breath", note:"Inhale through a curled tongue to cool down."},
             hi:{name:"शीतली", desc:"शीतल श्वास", note:"जीभ मोड़कर साँस लें, शरीर को ठंडक दें।"},
             or:{name:"ଶୀତଳୀ", desc:"ଶୀତଳ ଶ୍ୱାସ", note:"ଜିଭ ମୋଡ଼ି ଶ୍ୱାସ ନିଅନ୍ତୁ, ଶରୀରକୁ ଶୀତଳ କରନ୍ତୁ।"} } },

    { id:"kapalbhati", icon:"☀️", color:"#ff8a65", rounds:30,
      pattern:{inhale:1,holdIn:0,exhale:1,holdOut:0,rest:0},
      i18n:{ en:{name:"Kapalbhati", desc:"Skull-shining · energizing", note:"Sharp active exhale, passive inhale. Skip if pregnant."},
             hi:{name:"कपालभाति", desc:"ऊर्जादायी · तेज़ श्वास", note:"तेज़ साँस छोड़ें, सहज साँस लें। गर्भावस्था में न करें।"},
             or:{name:"କପାଳଭାତି", desc:"ଶକ୍ତିଦାୟକ · ଦ୍ରୁତ ଶ୍ୱାସ", note:"ଜୋର୍‌ରେ ନିଶ୍ୱାସ ଛାଡ଼ନ୍ତୁ, ସ୍ୱାଭାବିକ ଶ୍ୱାସ ନିଅନ୍ତୁ। ଗର୍ଭାବସ୍ଥାରେ ନୁହେଁ।"} } },

    { id:"energize", icon:"⚡", color:"#ffc24d", rounds:20,
      pattern:{inhale:2,holdIn:0,exhale:2,holdOut:0,rest:0},
      i18n:{ en:{name:"Energize", desc:"Quick 2-2 wake-up", note:"Quick breaths to feel alert."},
             hi:{name:"ऊर्जा श्वास", desc:"तेज़ 2-2 स्फूर्ति", note:"सतर्क महसूस करने के लिए तेज़ श्वास।"},
             or:{name:"ଶକ୍ତି ଶ୍ୱାସ", desc:"ଦ୍ରୁତ 2-2 ଚେତନା", note:"ସତର୍କ ଅନୁଭବ ପାଇଁ ଦ୍ରୁତ ଶ୍ୱାସ।"} } },

    { id:"kumbhak", icon:"🧘", color:"#ff5d6c", rounds:10, custom:true,
      pattern:{inhale:4,holdIn:30,exhale:6,holdOut:0,rest:5},
      i18n:{ en:{name:"Kumbhak Hold", desc:"Breath retention · customizable", note:"Hold the breath gently — never force it."},
             hi:{name:"कुम्भक", desc:"श्वास रोकना · अनुकूलन", note:"साँस को सहजता से रोकें — कभी ज़बरदस्ती न करें।"},
             or:{name:"କୁମ୍ଭକ", desc:"ଶ୍ୱାସ ଧାରଣ · ଅନୁକୂଳନ", note:"ଶ୍ୱାସକୁ ଧୀରେ ଧରନ୍ତୁ — କେବେ ବଳପୂର୍ବକ ନୁହେଁ।"} } },
  ],

  strings: {
    en: {
      tagline:"Breathing Studio", choose:"Choose a technique", begin:"Begin Session",
      soundCues:"Sound cues", voiceGuidance:"Voice guidance", safetyLink:"Safety guidelines",
      soundscape:"Soundscape", haptics:"Haptics (vibration)",
      planFree:"FREE", planPro:"PRO ✓",
      statSessions:"Sessions", statMinutes:"Minutes", statStreak:"Day Streak",
      upsellTitle:"Unlock Kumbhak Pro", upsellSub:"All techniques + breath-hold trainer · lifetime",
      upgradeTitle:"Kumbhak Pro ✨", upgradeSub:"One payment. Yours forever. No subscription.",
      perLifetime:"one-time · lifetime", priceNote:"🔒 Pay once — unlock on every device with your email.",
      benefit1:"Every technique unlocked — pranayama, Coherent & more",
      benefit2:"Kumbhak breath-hold trainer with custom rounds & hold times",
      benefit3:"Progress & streak synced across your devices",
      benefit4:"Guided programs (Sleep, Anxiety, Focus) & soundscapes",
      soon:"soon", unlock:"Unlock Pro", restore:"Restore purchase", later:"Maybe later",
      customRounds:"Rounds", customInhale:"Inhale", customHold:"Hold", customExhale:"Exhale",
      exit:"✕ Exit", pause:"Pause", resume:"Resume", restart:"Restart",
      ready:"Ready", getReady:"Get ready…", doneShort:"Done",
      roundOf:"Round {r} of {n}", roundsWord:"rounds",
      doneTitle:"Session complete", doneBtn:"Done",
      safetyTitle:"Breathe safely 🌬️", safetySub:"Please read before your first session.",
      safetyIntro:"Kumbhak is a wellness tool, not medical advice. Breath retention and paced breathing can cause lightheadedness.",
      safety1:"Practice sitting or lying down — never while driving, in water, or swimming.",
      safety2:"Stop immediately if you feel dizzy, faint, or short of breath.",
      safety3:"Consult a doctor first if you are pregnant or have heart conditions, epilepsy, or high blood pressure.",
      safety4:"Never force a breath-hold. Comfort over duration, always.",
      understand:"I understand",
      onboardTitle:"What brings you here?", onboardSub:"Pick a goal — we'll start you with a short, free session.",
      goalSleep:"Sleep", goalStress:"Less stress", goalFocus:"Focus", goalEnergy:"Energy", onboardSkip:"Skip for now",
      reminderLabel:"Daily reminder", reminderHint:"Works while the app is open. Install the app for reliable reminders.",
      reminderTitle:"Time to breathe 🧘", reminderBody:"A minute of breathing keeps your streak alive.",
      streakBadge:"🔥 {n}-day streak!",
      programsTitle:"Guided programs", dayProgress:"Day {d} / {n}", programDone:"Completed ✓", dayWord:"Day", last7:"Last 7 days",
      aiCardTitle:"AI Coach", aiCardSub:"A session shaped to how you feel",
      aiCoachTitle:"Your AI breathing coach", aiCoachSub:"Tell me how you feel — I'll compose a session for you.",
      moodQ:"How are you feeling?", minQ:"How many minutes?", compose:"Compose my session", composing:"Composing…", minShort:"min",
      mood_stressed:"Stressed", mood_anxious:"Anxious", mood_tired:"Tired", mood_focus:"Unfocused", mood_sleep:"Can't sleep", mood_okay:"Okay",
      coach_stressed:"Let's release that tension. Breathe out slowly and let your shoulders drop.",
      coach_anxious:"You're safe. We'll slow the breath to settle your mind.",
      coach_tired:"Let's wake up your energy with steady, even breaths.",
      coach_focus:"Let's steady your attention with a calm, square rhythm.",
      coach_sleep:"Let's wind down — long, soft exhales to ready you for sleep.",
      coach_okay:"Let's find a balanced, resonant rhythm together.",
      measBtn:"Measure your calm", measureTitle:"Measure your calm ❤️", measStartLabel:"Start",
      measIntro:"Measure your resting heart rate with the camera.",
      measHold:"Hold a fingertip gently over the rear camera.",
      measuring:"Measuring… {s}s — keep still.",
      measDone:"Your heart rate: {b} bpm.",
      measCalmer:"Nice — {d} bpm calmer than last time 🌿",
      measFail:"Couldn't read a clear pulse. Try again in good light.",
      measDenied:"Camera access is needed to measure.",
      phases:{ inhale:{label:"Breathe In", voice:"Breathe in"}, holdIn:{label:"Hold", voice:"Hold"},
               exhale:{label:"Breathe Out", voice:"Breathe out"}, holdOut:{label:"Hold", voice:"Hold"},
               rest:{label:"Rest", voice:"Rest"} },
    },
    hi: {
      tagline:"श्वास स्टूडियो", choose:"तकनीक चुनें", begin:"सत्र शुरू करें",
      soundCues:"ध्वनि संकेत", voiceGuidance:"आवाज़ मार्गदर्शन", safetyLink:"सुरक्षा दिशानिर्देश",
      soundscape:"साउंडस्केप", haptics:"हैप्टिक (कंपन)",
      planFree:"नि:शुल्क", planPro:"प्रो ✓",
      statSessions:"सत्र", statMinutes:"मिनट", statStreak:"लगातार दिन",
      upsellTitle:"कुम्भक प्रो अनलॉक करें", upsellSub:"सभी तकनीकें + श्वास-रोक ट्रेनर · आजीवन",
      upgradeTitle:"कुम्भक प्रो ✨", upgradeSub:"एक बार भुगतान। हमेशा के लिए आपका। कोई सब्सक्रिप्शन नहीं।",
      perLifetime:"एक बार · आजीवन", priceNote:"🔒 एक बार भुगतान करें — अपने ईमेल से हर डिवाइस पर अनलॉक।",
      benefit1:"सभी तकनीकें अनलॉक — प्राणायाम, कोहेरेंट और भी",
      benefit2:"कुम्भक श्वास-रोक ट्रेनर — अपनी पसंद के राउंड व समय",
      benefit3:"प्रगति व स्ट्रीक सभी डिवाइस पर सिंक",
      benefit4:"गाइडेड प्रोग्राम (नींद, चिंता, फोकस) व साउंडस्केप",
      soon:"जल्द", unlock:"प्रो अनलॉक करें", restore:"खरीद पुनर्स्थापित करें", later:"बाद में",
      customRounds:"राउंड", customInhale:"साँस लेना", customHold:"रोकना", customExhale:"साँस छोड़ना",
      exit:"✕ बाहर", pause:"रोकें", resume:"जारी रखें", restart:"फिर से",
      ready:"तैयार", getReady:"तैयार हो जाइए…", doneShort:"पूर्ण",
      roundOf:"राउंड {r} / {n}", roundsWord:"राउंड",
      doneTitle:"सत्र पूर्ण", doneBtn:"हो गया",
      safetyTitle:"सुरक्षित श्वास लें 🌬️", safetySub:"अपने पहले सत्र से पहले पढ़ें।",
      safetyIntro:"कुम्भक एक वेलनेस टूल है, चिकित्सकीय सलाह नहीं। साँस रोकने व नियंत्रित श्वास से चक्कर आ सकते हैं।",
      safety1:"बैठकर या लेटकर अभ्यास करें — गाड़ी चलाते, पानी में या तैरते समय कभी नहीं।",
      safety2:"चक्कर, बेहोशी या साँस फूलने पर तुरंत रुकें।",
      safety3:"गर्भावस्था, हृदय रोग, मिर्गी या उच्च रक्तचाप में पहले डॉक्टर से सलाह लें।",
      safety4:"साँस कभी ज़बरदस्ती न रोकें। अवधि से ज़्यादा आराम ज़रूरी है।",
      understand:"मैं समझ गया",
      onboardTitle:"आप यहाँ क्यों आए?", onboardSub:"एक लक्ष्य चुनें — हम एक छोटा, नि:शुल्क सत्र शुरू करेंगे।",
      goalSleep:"नींद", goalStress:"तनाव कम", goalFocus:"एकाग्रता", goalEnergy:"ऊर्जा", onboardSkip:"अभी छोड़ें",
      reminderLabel:"रोज़ाना रिमाइंडर", reminderHint:"ऐप खुला होने पर काम करता है। भरोसेमंद रिमाइंडर के लिए ऐप इंस्टॉल करें।",
      reminderTitle:"साँस लेने का समय 🧘", reminderBody:"एक मिनट की साँस आपकी स्ट्रीक बनाए रखती है।",
      streakBadge:"🔥 {n} दिन की स्ट्रीक!",
      programsTitle:"गाइडेड प्रोग्राम", dayProgress:"दिन {d} / {n}", programDone:"पूर्ण ✓", dayWord:"दिन", last7:"पिछले 7 दिन",
      aiCardTitle:"AI कोच", aiCardSub:"आपकी भावना के अनुसार सत्र",
      aiCoachTitle:"आपका AI श्वास कोच", aiCoachSub:"बताइए आप कैसा महसूस कर रहे हैं — मैं सत्र तैयार करूँगा।",
      moodQ:"आप कैसा महसूस कर रहे हैं?", minQ:"कितने मिनट?", compose:"मेरा सत्र बनाएँ", composing:"बना रहे हैं…", minShort:"मिनट",
      mood_stressed:"तनाव", mood_anxious:"चिंतित", mood_tired:"थका हुआ", mood_focus:"ध्यान नहीं", mood_sleep:"नींद नहीं", mood_okay:"ठीक",
      coach_stressed:"आइए तनाव छोड़ें। धीरे-धीरे साँस छोड़ें और कंधे ढीले करें।",
      coach_anxious:"आप सुरक्षित हैं। हम साँस धीमी कर मन को शांत करेंगे।",
      coach_tired:"आइए स्थिर, सम साँसों से ऊर्जा जगाएँ।",
      coach_focus:"आइए शांत, चौकोर लय से ध्यान स्थिर करें।",
      coach_sleep:"आइए विश्राम करें — लंबी, कोमल साँसें नींद के लिए।",
      coach_okay:"आइए मिलकर एक संतुलित, समस्वर लय पाएँ।",
      measBtn:"अपनी शांति मापें", measureTitle:"अपनी शांति मापें ❤️", measStartLabel:"शुरू करें",
      measIntro:"कैमरे से अपनी विश्राम हृदय गति मापें।",
      measHold:"उँगली को पिछले कैमरे पर हल्के से रखें।",
      measuring:"माप रहे हैं… {s}से — स्थिर रहें।",
      measDone:"आपकी हृदय गति: {b} bpm।",
      measCalmer:"बढ़िया — पिछली बार से {d} bpm शांत 🌿",
      measFail:"स्पष्ट नाड़ी नहीं मिली। अच्छी रोशनी में पुनः प्रयास करें।",
      measDenied:"मापने के लिए कैमरे की अनुमति चाहिए।",
      phases:{ inhale:{label:"साँस लें", voice:"साँस लें"}, holdIn:{label:"रोकें", voice:"रोकें"},
               exhale:{label:"साँस छोड़ें", voice:"छोड़ें"}, holdOut:{label:"रोकें", voice:"रोकें"},
               rest:{label:"विश्राम", voice:"विश्राम"} },
    },
    or: {
      tagline:"ଶ୍ୱାସ ଷ୍ଟୁଡିଓ", choose:"ଏକ ଅଭ୍ୟାସ ବାଛନ୍ତୁ", begin:"ସେସନ୍ ଆରମ୍ଭ କରନ୍ତୁ",
      soundCues:"ଧ୍ୱନି ସଙ୍କେତ", voiceGuidance:"ସ୍ୱର ମାର୍ଗଦର୍ଶନ", safetyLink:"ସୁରକ୍ଷା ନିର୍ଦ୍ଦେଶାବଳୀ",
      soundscape:"ସାଉଣ୍ଡସ୍କେପ୍", haptics:"ହାପ୍ଟିକ୍ (କମ୍ପନ)",
      planFree:"ମାଗଣା", planPro:"ପ୍ରୋ ✓",
      statSessions:"ସେସନ୍", statMinutes:"ମିନିଟ୍", statStreak:"ଲଗାତାର ଦିନ",
      upsellTitle:"କୁମ୍ଭକ ପ୍ରୋ ଅନଲକ୍ କରନ୍ତୁ", upsellSub:"ସମସ୍ତ ଅଭ୍ୟାସ + ଶ୍ୱାସ-ଧାରଣ ଟ୍ରେନର୍ · ଆଜୀବନ",
      upgradeTitle:"କୁମ୍ଭକ ପ୍ରୋ ✨", upgradeSub:"ଗୋଟିଏ ଦେୟ। ଚିରଦିନ ପାଇଁ ଆପଣଙ୍କର। କୌଣସି ସବସ୍କ୍ରିପସନ୍ ନାହିଁ।",
      perLifetime:"ଏକ-ଥର · ଆଜୀବନ", priceNote:"🔒 ଥରେ ଦେୟ କରନ୍ତୁ — ଇମେଲ୍ ସହ ପ୍ରତ୍ୟେକ ଡିଭାଇସ୍‌ରେ ଅନଲକ୍।",
      benefit1:"ସମସ୍ତ ଅଭ୍ୟାସ ଅନଲକ୍ — ପ୍ରାଣାୟାମ, କୋହେରେଣ୍ଟ ଓ ଅଧିକ",
      benefit2:"କୁମ୍ଭକ ଶ୍ୱାସ-ଧାରଣ ଟ୍ରେନର୍ — ନିଜ ପସନ୍ଦର ରାଉଣ୍ଡ ଓ ସମୟ",
      benefit3:"ପ୍ରଗତି ଓ ଷ୍ଟ୍ରିକ୍ ସମସ୍ତ ଡିଭାଇସ୍‌ରେ ସିଙ୍କ୍",
      benefit4:"ଗାଇଡେଡ୍ ପ୍ରୋଗ୍ରାମ (ନିଦ୍ରା, ଚିନ୍ତା, ଏକାଗ୍ରତା) ଓ ସାଉଣ୍ଡସ୍କେପ୍",
      soon:"ଶୀଘ୍ର", unlock:"ପ୍ରୋ ଅନଲକ୍ କରନ୍ତୁ", restore:"କ୍ରୟ ପୁନଃସ୍ଥାପନ", later:"ପରେ",
      customRounds:"ରାଉଣ୍ଡ", customInhale:"ଶ୍ୱାସ ନିଅନ୍ତୁ", customHold:"ଧରନ୍ତୁ", customExhale:"ଶ୍ୱାସ ଛାଡ଼ନ୍ତୁ",
      exit:"✕ ବାହାରନ୍ତୁ", pause:"ବିରତି", resume:"ପୁନଃଆରମ୍ଭ", restart:"ପୁନର୍ବାର",
      ready:"ପ୍ରସ୍ତୁତ", getReady:"ପ୍ରସ୍ତୁତ ହୁଅନ୍ତୁ…", doneShort:"ସମାପ୍ତ",
      roundOf:"ରାଉଣ୍ଡ {r} / {n}", roundsWord:"ରାଉଣ୍ଡ",
      doneTitle:"ସେସନ୍ ସମ୍ପୂର୍ଣ୍ଣ", doneBtn:"ହୋଇଗଲା",
      safetyTitle:"ସୁରକ୍ଷିତ ଭାବେ ଶ୍ୱାସ ନିଅନ୍ତୁ 🌬️", safetySub:"ପ୍ରଥମ ସେସନ୍ ପୂର୍ବରୁ ପଢ଼ନ୍ତୁ।",
      safetyIntro:"କୁମ୍ଭକ ଏକ ସୁସ୍ଥତା ଉପକରଣ, ଚିକିତ୍ସା ପରାମର୍ଶ ନୁହେଁ। ଶ୍ୱାସ ଧାରଣ ଓ ନିୟନ୍ତ୍ରିତ ଶ୍ୱାସ ମୁଣ୍ଡ ବୁଲାଇପାରେ।",
      safety1:"ବସି କିମ୍ବା ଶୋଇ ଅଭ୍ୟାସ କରନ୍ତୁ — ଗାଡ଼ି ଚଲାଇବା, ପାଣିରେ କିମ୍ବା ପହଁରିବା ସମୟରେ କେବେ ନୁହେଁ।",
      safety2:"ମୁଣ୍ଡ ବୁଲାଇଲେ, ଦୁର୍ବଳ ଲାଗିଲେ କିମ୍ବା ଶ୍ୱାସ ଅଭାବ ହେଲେ ତୁରନ୍ତ ବନ୍ଦ କରନ୍ତୁ।",
      safety3:"ଗର୍ଭବତୀ ଥିଲେ କିମ୍ବା ହୃଦ୍‌ରୋଗ, ମୃଗୀ, ଉଚ୍ଚ ରକ୍ତଚାପ ଥିଲେ ପ୍ରଥମେ ଡାକ୍ତରଙ୍କ ସହ ପରାମର୍ଶ କରନ୍ତୁ।",
      safety4:"ଶ୍ୱାସକୁ କେବେ ବଳପୂର୍ବକ ଧରନ୍ତୁ ନାହିଁ। ସମୟଠାରୁ ଆରାମ ସର୍ବଦା ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ।",
      understand:"ମୁଁ ବୁଝିଲି",
      onboardTitle:"ଆପଣ କାହିଁକି ଆସିଛନ୍ତି?", onboardSub:"ଏକ ଲକ୍ଷ୍ୟ ବାଛନ୍ତୁ — ଆମେ ଏକ ଛୋଟ, ମାଗଣା ସେସନ୍ ଆରମ୍ଭ କରିବୁ।",
      goalSleep:"ନିଦ୍ରା", goalStress:"କମ୍ ଚାପ", goalFocus:"ଏକାଗ୍ରତା", goalEnergy:"ଶକ୍ତି", onboardSkip:"ବର୍ତ୍ତମାନ ଛାଡ଼ନ୍ତୁ",
      reminderLabel:"ଦୈନିକ ସ୍ମାରକ", reminderHint:"ଆପ୍ ଖୋଲା ଥିଲେ କାମ କରେ। ନିର୍ଭରଯୋଗ୍ୟ ସ୍ମାରକ ପାଇଁ ଆପ୍ ଇନଷ୍ଟଲ୍ କରନ୍ତୁ।",
      reminderTitle:"ଶ୍ୱାସ ନେବାର ସମୟ 🧘", reminderBody:"ଗୋଟିଏ ମିନିଟ୍ ଶ୍ୱାସ ଆପଣଙ୍କ ଷ୍ଟ୍ରିକ୍ ବଞ୍ଚାଇ ରଖେ।",
      streakBadge:"🔥 {n}-ଦିନ ଷ୍ଟ୍ରିକ୍!",
      programsTitle:"ଗାଇଡେଡ୍ ପ୍ରୋଗ୍ରାମ", dayProgress:"ଦିନ {d} / {n}", programDone:"ସମ୍ପୂର୍ଣ୍ଣ ✓", dayWord:"ଦିନ", last7:"ଗତ 7 ଦିନ",
      aiCardTitle:"AI କୋଚ୍", aiCardSub:"ଆପଣଙ୍କ ଅନୁଭବ ଅନୁଯାୟୀ ସେସନ୍",
      aiCoachTitle:"ଆପଣଙ୍କ AI ଶ୍ୱାସ କୋଚ୍", aiCoachSub:"କୁହନ୍ତୁ ଆପଣ କେମିତି ଅନୁଭବ କରୁଛନ୍ତି — ମୁଁ ଆପଣଙ୍କ ପାଇଁ ସେସନ୍ ତିଆରି କରିବି।",
      moodQ:"ଆପଣ କେମିତି ଅନୁଭବ କରୁଛନ୍ତି?", minQ:"କେତେ ମିନିଟ୍?", compose:"ମୋ ସେସନ୍ ତିଆରି କରନ୍ତୁ", composing:"ତିଆରି ହେଉଛି…", minShort:"ମିନିଟ୍",
      mood_stressed:"ଚାପଗ୍ରସ୍ତ", mood_anxious:"ଚିନ୍ତିତ", mood_tired:"କ୍ଲାନ୍ତ", mood_focus:"ଅନେକାଗ୍ର", mood_sleep:"ନିଦ ନାହିଁ", mood_okay:"ଠିକ୍",
      coach_stressed:"ଆସନ୍ତୁ ସେହି ଚାପ ଛାଡ଼ିବା। ଧୀରେ ଧୀରେ ଶ୍ୱାସ ଛାଡ଼ନ୍ତୁ ଓ କାନ୍ଧ ହାଲୁକା କରନ୍ତୁ।",
      coach_anxious:"ଆପଣ ସୁରକ୍ଷିତ। ଆମେ ଶ୍ୱାସ ଧୀର କରି ମନ ଶାନ୍ତ କରିବୁ।",
      coach_tired:"ଆସନ୍ତୁ ସ୍ଥିର, ସମାନ ଶ୍ୱାସରେ ଶକ୍ତି ଜଗାଇବା।",
      coach_focus:"ଆସନ୍ତୁ ଶାନ୍ତ, ବର୍ଗାକାର ଲୟରେ ଧ୍ୟାନ ସ୍ଥିର କରିବା।",
      coach_sleep:"ଆସନ୍ତୁ ବିଶ୍ରାମ କରିବା — ନିଦ ପାଇଁ ଲମ୍ବା, କୋମଳ ଶ୍ୱାସ।",
      coach_okay:"ଆସନ୍ତୁ ମିଳିତ ଭାବେ ଏକ ସନ୍ତୁଳିତ ଲୟ ପାଇବା।",
      measBtn:"ଆପଣଙ୍କ ଶାନ୍ତି ମାପନ୍ତୁ", measureTitle:"ଆପଣଙ୍କ ଶାନ୍ତି ମାପନ୍ତୁ ❤️", measStartLabel:"ଆରମ୍ଭ",
      measIntro:"କ୍ୟାମେରା ସହ ଆପଣଙ୍କ ବିଶ୍ରାମ ହୃଦ୍‌ସ୍ପନ୍ଦନ ମାପନ୍ତୁ।",
      measHold:"ପଛ କ୍ୟାମେରା ଉପରେ ଆଙ୍ଗୁଠି ଧୀରେ ରଖନ୍ତୁ।",
      measuring:"ମାପୁଛି… {s}ସେ — ସ୍ଥିର ରୁହନ୍ତୁ।",
      measDone:"ଆପଣଙ୍କ ହୃଦ୍‌ସ୍ପନ୍ଦନ: {b} bpm।",
      measCalmer:"ବାହ୍ — ଗତ ଥରଠାରୁ {d} bpm ଶାନ୍ତ 🌿",
      measFail:"ସ୍ପଷ୍ଟ ନାଡ଼ି ମିଳିଲା ନାହିଁ। ଭଲ ଆଲୋକରେ ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
      measDenied:"ମାପିବା ପାଇଁ କ୍ୟାମେରା ଅନୁମତି ଆବଶ୍ୟକ।",
      phases:{ inhale:{label:"ଶ୍ୱାସ ନିଅନ୍ତୁ", voice:"ଶ୍ୱାସ ନିଅନ୍ତୁ"}, holdIn:{label:"ଧରନ୍ତୁ", voice:"ଧରନ୍ତୁ"},
               exhale:{label:"ଶ୍ୱାସ ଛାଡ଼ନ୍ତୁ", voice:"ଛାଡ଼ନ୍ତୁ"}, holdOut:{label:"ଧରନ୍ତୁ", voice:"ଧରନ୍ତୁ"},
               rest:{label:"ବିଶ୍ରାମ", voice:"ବିଶ୍ରାମ"} },
    },
  },
};
